main: com.perceivedev.hydrusenchants.HydrusEnchants
name: CustomEnchants
version: 1.0.0
description: A bukkit plugin
authors: [Rayzr, I Al Istannen]
commands:
  essentialenchants:
    description: The EssentialEnchants main command
    aliases: [ee,enchants,enchant]
    usage: "\u00A7cSomething went horribly, terribly wrong!"
    permission: CustomEnchants.main
