main: com.perceivedev.hydrusenchants.HydrusEnchants
name: HydrusEnchants
version: 1.0.0
description: A bukkit plugin
authors: [Rayzr, I Al Istannen]
commands:
  hyrdusce:
    description: HydrusEnchants main command
    aliases: [hyrdusenchants,hce]
    usage: "/hyrdusce [command]"
    permission: HydrusEnchants.main
