main: com.perceivedev.hydrusenchants.HydrusEnchants
name: HydrusEnchants
version: 1.0.0
description: A bukkit plugin
author: [Rayzr]
#depend: [PerceiveCore]
commands:
  hyrdusce:
    description: HydrusEnchants main command
    aliases: [hyrdusenchants,hce]
    usage: "/hyrdusce [command]"
    permission: HydrusEnchants.main
